# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Hannah Soyer
tagline:          'Your tagline'
description:      A student at the University of Iowa majoring in English and Journalism, with an emphasis in creative nonfiction writing.
url:              http://hsoyer.github.io
baseurl:          /profile-hyde/
shortbaseurl:     /profile-hyde
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Hannah Soyer'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

